import config.Config;
import server.Server;
import utils.Utils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

  public App() {
    Config.initConfig();
    Config.SKU_OBJECTS = Utils.readJsonFile(Config.FILE_PATH);

    // Start server.
    Server.getInstance().start();
  }

  public static void main(String[] args) {
    new App();
  }
}
